
"""
This module is the console entry point when setup.py was used to install
cyther. This module is also run with the -m option from the terminal
"""

import sys
from .arguments import parser


def main(args=None):
    """
    Entry point for cyther-script, generated by setup.py on installation
    """
    if args is None:
        args = sys.argv[1:]

    if not args:
        args = ['-h']

    namespace = parser.parse_args(args)
    entry_function = namespace.func
    del namespace.func
    kwargs = namespace.__dict__
    return entry_function(**kwargs)
